In [1]:
import pandas as pd
data_url = 'https://andybek.com/pandas-soccer'
players = pd.read_csv(data_url)
players.head(n=2)

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0

In [2]:
players.market_value.sort_values(ascending=False)

96     75.00
267    75.00
0      65.00
244    65.00
245    65.00
       ...
287     0.10
113     0.05
30       NaN
192      NaN
195      NaN
Name: market_value, Length: 465, dtype: float64

In [3]:
players.sort_values(by='market_value', ascending=False)

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
96,Eden Hazard,Chelsea,26,LW,1,75.00,4220,10.5,2.30%,224,2,Belgium,0,3,5,1,0
267,Paul Pogba,Manchester+United,24,CM,2,75.00,7435,8.0,19.50%,115,2,France,0,2,12,1,1
0,Alexis Sanchez,Arsenal,28,LW,1,65.00,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
244,Kevin De Bruyne,Manchester+City,26,AM,1,65.00,2252,10.0,17.50%,199,2,Belgium,0,3,11,1,0
245,Sergio Aguero,Manchester+City,29,CF,1,65.00,4046,11.5,9.70%,175,3,Argentina,0,4,11,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,Joel Castro Pereira,Manchester+United,21,GK,4,0.10,395,4.0,1.00%,6,2,Portugal,0,1,12,1,0
113,Eduardo Carvalho,Chelsea,34,LW,1,0.05,467,5.0,0.10%,0,2,Portugal,0,6,5,1,1
30,Granit Xhaka,Arsenal,24,NaN,2,NaN,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
192,Steve Mounie,Huddersfield,22,CF,1,NaN,56,6.0,0.60%,0,2,Benin,0,2,8,0,0
195,Kasper Schmeichel,Leicester+City,30,GK,4,NaN,1601,5.0,2.40%,109,2,Denmark,0,4,9,0,0

In [4]:
players.sort_index(ascending=False)

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
464,Diafra Sakho,West+Ham,27,CF,1,10.0,214,5.5,0.10%,12,4,Senegal,0,3,20,0,0
463,Ashley Fletcher,West+Ham,21,CF,1,1.0,412,4.5,5.90%,16,1,England,0,1,20,0,1
462,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0
461,Arthur Masuaku,West+Ham,23,LB,3,7.0,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1
460,Edimilson Fernandes,West+Ham,21,CM,2,5.0,288,4.5,0.40%,38,2,Switzerland,0,1,20,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0

In [5]:
players.index

RangeIndex(start=0, stop=465, step=1)

In [8]:
players.set_index('name' , inplace=True)

In [9]:
players.head(n=10)

,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
name,,,,,,,,,,,,,,,,
Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0
Hector Bellerin,Arsenal,22,RB,3,30.0,1675,6.0,13.70%,119,2,Spain,0,2,1,1,0
Olivier Giroud,Arsenal,30,CF,1,22.0,2230,8.5,2.50%,116,2,France,0,4,1,1,0
Nacho Monreal,Arsenal,31,LB,3,13.0,555,5.5,4.70%,115,2,Spain,0,4,1,1,0
Shkodran Mustafi,Arsenal,25,CB,3,30.0,1877,5.5,4.00%,90,2,Germany,0,3,1,1,1
Alex Iwobi,Arsenal,21,LW,1,10.0,1812,5.5,1.00%,89,4,Nigeria,0,1,1,1,0

In [10]:
players.sort_index(ascending=False)

,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
name,,,,,,,,,,,,,,,,
Åukasz FabiaÅ„ski,Swansea,32,GK,4,9.0,285,4.5,6.20%,116,2,Poland,0,5,16,0,0
Ã€ngel Rangel,Swansea,34,RB,3,1.0,137,4.0,18.80%,26,2,Spain,0,6,16,0,0
Ã‰tienne Capoue,Watford,29,DM,2,9.0,412,5.5,8.00%,131,2,France,0,4,18,0,0
YounÃ¨s Kaboul,Watford,31,CB,3,2.5,263,4.5,0.10%,57,2,France,0,4,18,0,1
Yohan Cabaye,Crystal+Palace,31,CM,2,15.0,456,5.5,1.40%,91,2,France,0,4,6,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abdoulaye Doucoure,Watford,24,CM,2,6.0,124,5.0,0.00%,38,2,France,0,2,18,0,0
Aaron Ramsey,Arsenal,26,CM,2,35.0,1040,7.0,5.10%,56,1,Wales,0,3,1,1,0
Aaron Mooy,Huddersfield,26,CM,2,5.0,588,5.5,2.50%,0,4,Australia,0,3,8,0,0
Aaron Lennon,Everton,30,RW,1,5.0,504,5.5,0.20%,22,1,England,0,4,7,0,0
Aaron Cresswell,West+Ham,27,LB,3,12.0,380,5.0,1.30%,60,1,England,0,3,20,0,0

In [11]:
players.sort_index().head(n=10)

,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
name,,,,,,,,,,,,,,,,
Aaron Cresswell,West+Ham,27,LB,3,12.0,380,5.0,1.30%,60,1,England,0,3,20,0,0
Aaron Lennon,Everton,30,RW,1,5.0,504,5.5,0.20%,22,1,England,0,4,7,0,0
Aaron Mooy,Huddersfield,26,CM,2,5.0,588,5.5,2.50%,0,4,Australia,0,3,8,0,0
Aaron Ramsey,Arsenal,26,CM,2,35.0,1040,7.0,5.10%,56,1,Wales,0,3,1,1,0
Abdoulaye Doucoure,Watford,24,CM,2,6.0,124,5.0,0.00%,38,2,France,0,2,18,0,0
Adam Federici,Bournemouth,32,GK,4,1.0,126,4.0,1.50%,8,4,Australia,0,5,2,0,0
Adam Lallana,Liverpool,29,AM,1,25.0,1808,7.5,6.40%,139,1,England,0,4,10,1,0
Adam Smith,Bournemouth,26,RB,3,5.0,200,5.0,0.90%,104,1,England,0,3,2,0,0
Ademola Lookman,Everton,19,LW,1,5.0,1387,5.5,0.30%,16,1,England,0,1,7,0,0
Adrian,West+Ham,30,GK,4,8.0,266,4.5,0.80%,64,2,Spain,0,4,20,0,0

In [12]:
players.sort_index(inplace=True)

In [13]:
players.head(n=10)

,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
name,,,,,,,,,,,,,,,,
Aaron Cresswell,West+Ham,27,LB,3,12.0,380,5.0,1.30%,60,1,England,0,3,20,0,0
Aaron Lennon,Everton,30,RW,1,5.0,504,5.5,0.20%,22,1,England,0,4,7,0,0
Aaron Mooy,Huddersfield,26,CM,2,5.0,588,5.5,2.50%,0,4,Australia,0,3,8,0,0
Aaron Ramsey,Arsenal,26,CM,2,35.0,1040,7.0,5.10%,56,1,Wales,0,3,1,1,0
Abdoulaye Doucoure,Watford,24,CM,2,6.0,124,5.0,0.00%,38,2,France,0,2,18,0,0
Adam Federici,Bournemouth,32,GK,4,1.0,126,4.0,1.50%,8,4,Australia,0,5,2,0,0
Adam Lallana,Liverpool,29,AM,1,25.0,1808,7.5,6.40%,139,1,England,0,4,10,1,0
Adam Smith,Bournemouth,26,RB,3,5.0,200,5.0,0.90%,104,1,England,0,3,2,0,0
Ademola Lookman,Everton,19,LW,1,5.0,1387,5.5,0.30%,16,1,England,0,1,7,0,0
Adrian,West+Ham,30,GK,4,8.0,266,4.5,0.80%,64,2,Spain,0,4,20,0,0

In [14]:
players.sort_index(ascending=False, inplace=True)

In [15]:
players.head(n=10)

,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
name,,,,,,,,,,,,,,,,
Åukasz FabiaÅ„ski,Swansea,32,GK,4,9.0,285,4.5,6.20%,116,2,Poland,0,5,16,0,0
Ã€ngel Rangel,Swansea,34,RB,3,1.0,137,4.0,18.80%,26,2,Spain,0,6,16,0,0
Ã‰tienne Capoue,Watford,29,DM,2,9.0,412,5.5,8.00%,131,2,France,0,4,18,0,0
YounÃ¨s Kaboul,Watford,31,CB,3,2.5,263,4.5,0.10%,57,2,France,0,4,18,0,1
Yohan Cabaye,Crystal+Palace,31,CM,2,15.0,456,5.5,1.40%,91,2,France,0,4,6,0,0
Yohan Benalouane,Leicester+City,30,CB,3,1.0,305,4.5,0.10%,27,4,Tunisia,0,4,9,0,0
Yaya Toure,Manchester+City,34,CM,2,8.0,2318,6.5,2.50%,86,4,Cote d'Ivoire,0,6,11,1,0
Yannick Bolasie,Everton,28,LW,1,20.0,896,6.5,0.20%,45,4,Congo DR,0,4,7,0,1
Xherdan Shaqiri,Stoke+City,25,RW,1,15.0,1000,6.0,3.20%,80,2,Switzerland,0,3,15,0,0
Winston Reid,West+Ham,29,CB,3,10.0,338,5.0,0.40%,102,4,New Zealand,0,4,20,0,0

In [16]:
players.sort_index(axis=1)

,age,age_cat,big_club,club,club_id,fpl_points,fpl_sel,fpl_value,market_value,nationality,new_foreign,new_signing,page_views,position,position_cat,region
name,,,,,,,,,,,,,,,,
Åukasz FabiaÅ„ski,32,5,0,Swansea,16,116,6.20%,4.5,9.0,Poland,0,0,285,GK,4,2
Ã€ngel Rangel,34,6,0,Swansea,16,26,18.80%,4.0,1.0,Spain,0,0,137,RB,3,2
Ã‰tienne Capoue,29,4,0,Watford,18,131,8.00%,5.5,9.0,France,0,0,412,DM,2,2
YounÃ¨s Kaboul,31,4,0,Watford,18,57,0.10%,4.5,2.5,France,0,1,263,CB,3,2
Yohan Cabaye,31,4,0,Crystal+Palace,6,91,1.40%,5.5,15.0,France,0,0,456,CM,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abdoulaye Doucoure,24,2,0,Watford,18,38,0.00%,5.0,6.0,France,0,0,124,CM,2,2
Aaron Ramsey,26,3,1,Arsenal,1,56,5.10%,7.0,35.0,Wales,0,0,1040,CM,2,1
Aaron Mooy,26,3,0,Huddersfield,8,0,2.50%,5.5,5.0,Australia,0,0,588,CM,2,4
Aaron Lennon,30,4,0,Everton,7,22,0.20%,5.5,5.0,England,0,0,504,RW,1,1
Aaron Cresswell,27,3,0,West+Ham,20,60,1.30%,5.0,12.0,England,0,0,380,LB,3,1

In [17]:
players.sort_index(axis=1, inplace=True)

In [18]:
players.reset_index(inplace=True)

In [19]:
players.head(n=10)

,name,age,age_cat,big_club,club,club_id,fpl_points,fpl_sel,fpl_value,market_value,nationality,new_foreign,new_signing,page_views,position,position_cat,region
0,Åukasz FabiaÅ„ski,32,5,0,Swansea,16,116,6.20%,4.5,9.0,Poland,0,0,285,GK,4,2
1,Ã€ngel Rangel,34,6,0,Swansea,16,26,18.80%,4.0,1.0,Spain,0,0,137,RB,3,2
2,Ã‰tienne Capoue,29,4,0,Watford,18,131,8.00%,5.5,9.0,France,0,0,412,DM,2,2
3,YounÃ¨s Kaboul,31,4,0,Watford,18,57,0.10%,4.5,2.5,France,0,1,263,CB,3,2
4,Yohan Cabaye,31,4,0,Crystal+Palace,6,91,1.40%,5.5,15.0,France,0,0,456,CM,2,2
5,Yohan Benalouane,30,4,0,Leicester+City,9,27,0.10%,4.5,1.0,Tunisia,0,0,305,CB,3,4
6,Yaya Toure,34,6,1,Manchester+City,11,86,2.50%,6.5,8.0,Cote d'Ivoire,0,0,2318,CM,2,4
7,Yannick Bolasie,28,4,0,Everton,7,45,0.20%,6.5,20.0,Congo DR,0,1,896,LW,1,4
8,Xherdan Shaqiri,25,3,0,Stoke+City,15,80,3.20%,6.0,15.0,Switzerland,0,0,1000,RW,1,2
9,Winston Reid,29,4,0,West+Ham,20,102,0.40%,5.0,10.0,New Zealand,0,0,338,CB,3,4

In [20]:
players.reset_index(inplace=True)

In [21]:
players.head(n=10)

,index,name,age,age_cat,big_club,club,club_id,fpl_points,fpl_sel,fpl_value,market_value,nationality,new_foreign,new_signing,page_views,position,position_cat,region
0,0,Åukasz FabiaÅ„ski,32,5,0,Swansea,16,116,6.20%,4.5,9.0,Poland,0,0,285,GK,4,2
1,1,Ã€ngel Rangel,34,6,0,Swansea,16,26,18.80%,4.0,1.0,Spain,0,0,137,RB,3,2
2,2,Ã‰tienne Capoue,29,4,0,Watford,18,131,8.00%,5.5,9.0,France,0,0,412,DM,2,2
3,3,YounÃ¨s Kaboul,31,4,0,Watford,18,57,0.10%,4.5,2.5,France,0,1,263,CB,3,2
4,4,Yohan Cabaye,31,4,0,Crystal+Palace,6,91,1.40%,5.5,15.0,France,0,0,456,CM,2,2
5,5,Yohan Benalouane,30,4,0,Leicester+City,9,27,0.10%,4.5,1.0,Tunisia,0,0,305,CB,3,4
6,6,Yaya Toure,34,6,1,Manchester+City,11,86,2.50%,6.5,8.0,Cote d'Ivoire,0,0,2318,CM,2,4
7,7,Yannick Bolasie,28,4,0,Everton,7,45,0.20%,6.5,20.0,Congo DR,0,1,896,LW,1,4
8,8,Xherdan Shaqiri,25,3,0,Stoke+City,15,80,3.20%,6.0,15.0,Switzerland,0,0,1000,RW,1,2
9,9,Winston Reid,29,4,0,West+Ham,20,102,0.40%,5.0,10.0,New Zealand,0,0,338,CB,3,4

In [22]:
players.reset_index(inplace=True)

In [23]:
players.head(n=10)

,level_0,index,name,age,age_cat,big_club,club,club_id,fpl_points,fpl_sel,fpl_value,market_value,nationality,new_foreign,new_signing,page_views,position,position_cat,region
0,0,0,Åukasz FabiaÅ„ski,32,5,0,Swansea,16,116,6.20%,4.5,9.0,Poland,0,0,285,GK,4,2
1,1,1,Ã€ngel Rangel,34,6,0,Swansea,16,26,18.80%,4.0,1.0,Spain,0,0,137,RB,3,2
2,2,2,Ã‰tienne Capoue,29,4,0,Watford,18,131,8.00%,5.5,9.0,France,0,0,412,DM,2,2
3,3,3,YounÃ¨s Kaboul,31,4,0,Watford,18,57,0.10%,4.5,2.5,France,0,1,263,CB,3,2
4,4,4,Yohan Cabaye,31,4,0,Crystal+Palace,6,91,1.40%,5.5,15.0,France,0,0,456,CM,2,2
5,5,5,Yohan Benalouane,30,4,0,Leicester+City,9,27,0.10%,4.5,1.0,Tunisia,0,0,305,CB,3,4
6,6,6,Yaya Toure,34,6,1,Manchester+City,11,86,2.50%,6.5,8.0,Cote d'Ivoire,0,0,2318,CM,2,4
7,7,7,Yannick Bolasie,28,4,0,Everton,7,45,0.20%,6.5,20.0,Congo DR,0,1,896,LW,1,4
8,8,8,Xherdan Shaqiri,25,3,0,Stoke+City,15,80,3.20%,6.0,15.0,Switzerland,0,0,1000,RW,1,2
9,9,9,Winston Reid,29,4,0,West+Ham,20,102,0.40%,5.0,10.0,New Zealand,0,0,338,CB,3,4

In [25]:
players.drop('level_0', axis=1, inplace=True)

In [26]:
players.drop('index',axis=1, inplace=True)

In [27]:
players.head(n=10)

,name,age,age_cat,big_club,club,club_id,fpl_points,fpl_sel,fpl_value,market_value,nationality,new_foreign,new_signing,page_views,position,position_cat,region
0,Åukasz FabiaÅ„ski,32,5,0,Swansea,16,116,6.20%,4.5,9.0,Poland,0,0,285,GK,4,2
1,Ã€ngel Rangel,34,6,0,Swansea,16,26,18.80%,4.0,1.0,Spain,0,0,137,RB,3,2
2,Ã‰tienne Capoue,29,4,0,Watford,18,131,8.00%,5.5,9.0,France,0,0,412,DM,2,2
3,YounÃ¨s Kaboul,31,4,0,Watford,18,57,0.10%,4.5,2.5,France,0,1,263,CB,3,2
4,Yohan Cabaye,31,4,0,Crystal+Palace,6,91,1.40%,5.5,15.0,France,0,0,456,CM,2,2
5,Yohan Benalouane,30,4,0,Leicester+City,9,27,0.10%,4.5,1.0,Tunisia,0,0,305,CB,3,4
6,Yaya Toure,34,6,1,Manchester+City,11,86,2.50%,6.5,8.0,Cote d'Ivoire,0,0,2318,CM,2,4
7,Yannick Bolasie,28,4,0,Everton,7,45,0.20%,6.5,20.0,Congo DR,0,1,896,LW,1,4
8,Xherdan Shaqiri,25,3,0,Stoke+City,15,80,3.20%,6.0,15.0,Switzerland,0,0,1000,RW,1,2
9,Winston Reid,29,4,0,West+Ham,20,102,0.40%,5.0,10.0,New Zealand,0,0,338,CB,3,4